[project]
name = "priors"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.9"
dependencies = [
    "datapane>=0.17.0",
    "numpy>=2.0.2",
    "pandas>=1.5.3",
    "scikit-learn>=1.5.2",
    "sentence-transformers>=3.2.1",
    "tensorflow>=2.18.0",
]
